services:
  - type: web
    name: portflow-backend
    env: node
    plan: free
    buildCommand: yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_USER
        sync: false
      - key: MONGO_KEY
        sync: false
      - key: MONGO_HOST
        sync: false
      - key: MONGO_DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: portflow-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://tcc-portflow-phg6.onrender.com
